### ISSUE TITLE
Relative markers

### ISSUE THREAD

**Issue by jacob-seiler** [danrahn/MarkerEditorForPlex#16]
**Is your feature request related to a problem? Please describe.**
Not a bug, but when adding credits (especially in bulk) I would like to be able to relatively set a marker to (for example) the last 30 seconds of an episode. This is especially useful in cases where each episode could be a different length but have the same credits length.

**Describe the solution you'd like**
Perhaps when entering a negative time, it is calculates as milliseconds subtracted from the total time.

**Describe alternatives you've considered**
Manually figuring out times for every episode.

**Additional context**
N/A, can add if requested.

**Comment by danrahn** [comment]
Thanks for the suggestion! I like the idea of "negative timestamp == offset from the end." I should be able to get around to this sometime this week.

**Comment by jacob-seiler** [comment]
Also just thought of maybe something that lets you do relative from start time. So if you know an intro is 30 seconds maybe you can do +30 and it will take the start time and add 30 to it. That idea is less fleshed out though haha.

**Comment by danrahn** [comment]
The negative timestamps should be implemented in this commit: 918c86ea53527fcd6b6cde6a2b424352c5264076. It might take longer for it to reach a beta/main release though, since there are a bunch of other in-progress changes that I don't quite feel comfortable putting in an official release yet (and I was too lazy to create a feature branch for the work).

As for the relative start time, would that just be to avoid having to do the math/extra typing of "1:43.352 plus 30 seconds is 2:13.352," and instead do something like "1:43.352, +30.0" or are there other benefits that I'm not thinking of off the top of my head?

**Comment by danrahn** [comment]
Marking this as closed, since the initial request is in the latest beta, but let me know if you have more thoughts on the positive offset, or run into issues with the current negative offset implementation.
