### ISSUE TITLE
Editing markers for content hosted on other devices

### ISSUE THREAD

**Issue by MrPickles2009** [danrahn/MarkerEditorForPlex#17]
**Describe the solution you'd like**
I briefly looked through your code and don't know how possible this is but, it would be really nice to edit the intros and credits on my content hosted on my other devices.

**Additional context**
The majority of my plex content is hosted on my Nvidia SHIELD TV Pro but I don't have a way currently to modify the markers for that content, only the content hosted on my PC.

**Comment by danrahn** [comment]
The application needs direct access to the database, so just being able to connect to the server won't work. You can [make that location user-accessible on your Shield](https://support.plex.tv/articles/moving-server-data-storage-location-on-nvidia-shield/), and if that location can then be accessed via e.g. a network path that would work, since you can [override the database path](https://github.com/danrahn/MarkerEditorForPlex/wiki/configuration#database). Or you could shut down Plex, copy the database to your PC, make your edits, then overwrite the database on your Shield.

**Comment by danrahn** [comment]
Closing, as it's not possible to edit markers without direct access to the database, and there are no plans to get this application working directly on Shield servers (outside of the workarounds mentioned previously).
