### ISSUE TITLE
Bulk Add - dynamic markers

### ISSUE THREAD

**Issue by bassterror** [danrahn/MarkerEditorForPlex#29]
Let's say I know that every episode in a show has the last 40 seconds as credits. It will be great if we can bulk add credits to every episode by populating the start and end of a marker dynamically for each episode, given the fact that each episode has different duration. I don't see how this will be possible at the moment. I'm sorry if it is and I'm just too stupid to figure out.

Possible implementation:
To have these, let's say tokens, with `{` `}` or `[` `]` brackets (can be placed with a keyboard shortcut, or to have buttons for them, or just a legend explaining them), which we can use to make a "formula" to apply on each episode.
For example:
Start of the credit marker - {END}-00:40
End of the credit marker - {END}

![bulk](https://github.com/user-attachments/assets/49110907-bd15-4703-aa57-7c7296dc5c9a)

Probably there can be more tokens, not just the {END} one, but nothing comes to my mind at the moment. Maybe {LASTCHAPT}, {FIRSTCHAPT}, {#3CHAPT}, etc.

**Comment by danrahn** [comment]
The way I implemented this was with negative values (briefly documented [here](https://github.com/danrahn/MarkerEditorForPlex/wiki/usage#negative-timestamps)). So `-0:40` is 40 seconds from the end of the episode, and `-0` would be the end of the episode:

![image](https://github.com/user-attachments/assets/ed1fc345-6edb-4b59-8e02-a0a5ea651fd2)

Additional tokens aren't a bad idea though, as well as better in-app help, as I'm sure I've made plenty of questionable design decisions that aren't obvious (like not being able to use `[]` or `{}` as token identifiers, since they're already used as shortcuts to add/remove time from the timestamps). I'll close this out, since I think the core request is already implemented, but I'll keep the other ideas in mind.
